spring:
  application:
    name: hello-spring-cloud-web-admin-feign
  zipkin:
    base-url: http://localhost:7008
server:
  port: 7005

feign:
  hystrix:
    enabled: tru

eureka:
 client:
   service-url:
     defaultZone: http://localhost:7001/eureka/

