spring:
  application:
    name: itoken-service-sso
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource

    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/itoken-service-admin?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      name: root
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      password: 111111
      username: root
  zipkin:
    base-url: http://localhost:7008
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
  boot:
    admin:
      client:
        url: http://localhost:7009
server:
  port: 8012

feign:
  hystrix:
    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: ["health","info"]

mybatis:
  type-aliases-package: com.funtl.itoken.common.domain
  mapper-locations: classpath:mapper/*.xml