spring:
  application:
    name: itoken-service-redis
  boot:
    admin:
      client:
        url: http://localhost:7009
  zipkin:
    base-url: http://localhost:7008
  redis:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
    host: 127.0.0.1
    database: 0
    port: 6379
    password:


server:
  port: 8502

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7001/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: ["health","info"]