spring:
  application:
    name: itoken-admin
  zipkin:
    base-url: http://localhost:7008
server:
  port: 7009
eureka:
 client:
   service-url:
     defaultZone: http://localhost:7001/eureka/
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: ["health","info"]
