spring:
  application:
    name: itoken-service-admin
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource

    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/itoken-service-admin?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      name: root
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      password: 111111
      username: root
  zipkin:
    base-url: http://localhost:7008

  boot:
    admin:
      client:
        url: http://localhost:7009
server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: ["health","info"]

mybatis:
  type-aliases-package: com.funtl.itoken.service.admin.domain
  mapper-locations: classpath:mapper/*.xml